name: simple-web-eks-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/simple-web-win
      DOCKER_TAG: ${{ github.run_number }}

    steps:
      - name: 1. 소스코드 다운로드
        uses: actions/checkout@v4 

      - name: 2. Docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-web:${{ env.DOCKER_TAG }} .

      - name: 3. Docker 로그인
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true

      - name: 4. Docker 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-web:${{ env.DOCKER_TAG }}

      # dangtong은 내 레포지토리가 아니고 내 레포지토리도 simple-service라는 레포가 없어 주석
      #- name: 5. 서비스 리포지토리 체크아웃  
      #  uses: actions/checkout@v4
      #  with:
      #    repository: dangtong-s-inc/simple-service  
      #    ref: main
      #   path: .
      #    token: ${{ secrets.PAT }} 

     # deploy.yml에 명시된 이미지를 수정하기 위해 sed 구문으로 변경
      - name: 6. 쿠버네티스 매니페스트 파일 이미지 태그 업데이트 
        run: |
          echo ":: Updating image tag in simple-deploy.yaml ::"
          sed -i "s|image: .*|image: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}|g" simple-deploy.yaml
          cat simple-deploy.yaml

    # 5번 작업을 생략하여 다른 레포로 푸쉬할 일이 없기에 주석처리 
     # - name: 7. 변경사항 커밋 및 푸시  
     #   run: |
     #     git config --global user.name 'github-actions[bot]'
     #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
     #     git commit -am "Update image tag to ${{ env.DOCKER_TAG }}"
     #     git remote set-url origin https://${{ secrets.PAT }}@github.com/dangtong-s-inc/simple-service.git
     #     git push origin main

      - name: 8. AWS 인증
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: 9. EKS kubeconfig 업데이트
        run: aws eks update-kubeconfig --name simple-web-eks-ci

      - name: 10. 쿠버네티스 매니페스트 적용
        run: kubectl apply -f simple-deploy.yaml
